import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../src/components/header/header";
import React from "react";
import { EventCategoryCard } from "../src/components/EventCategoryCard/EventCategoryCard";

const inter = Inter({ subsets: ["latin"] });

interface PageProps {
    title: string;
    eventCategories: [any];
}

export default function Home({ title, eventCategories }: PageProps) {
    console.table(eventCategories);
    return (
        <>
            <Head>
                <title>Events App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />

                <h1>{title}</h1>

                {eventCategories.map(({ id, title, description, image }) => (
                    <EventCategoryCard
                        key={`EventCategoryCard-${id}`}
                        id={id}
                        title={title}
                        description={description}
                        image={image}
                    />
                ))}
            </main>
        </>
    );
}

export async function getServerSideProps() {
    const { events_categories } = await import("../data/data.json");

    return {
        props: {
            eventCategories: events_categories,
        },
    };
}
